/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'preprocess.debug+HP' 
 * Target:  'debug+HP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.24.11 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.24.8 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define TF_LITE_DISABLE_X86_NEON 1
        //#define TF_LITE_STRIP_ERROR_STRINGS 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
