/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'blinky.debug+HE' 
 * Target:  'debug+HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"

/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
